services:
  db:
    # https://hub.docker.com/_/postgres
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  keydb:
    image: eqalpha/keydb
    command: keydb-server /etc/keydb/redis.conf --server-threads 2  --maxmemory 16mb  --maxmemory-policy allkeys-lru  --maxmemory-samples 5
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - KEYDB_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - KEYDB_PASSWORD=${KEYDB_PASSWORD}
    ports:
      - 6379:6379
